//https://en.wikipedia.org/wiki/NASDAQ-100#Components

module.exports = [
	{name: '21st Century Fox', ticker: 'FOX'},
	{name: 'Activision Blizzard', ticker: 'ATVI'},
	{name: 'Adobe', ticker: 'ADBE'},
	{name: 'Akamai', ticker: 'AKAM'},
	{name: 'Alexion', ticker: 'ALXN'},
	{name: 'Alphabet Inc', ticker: 'GOOG'},
	{name: 'Amazon', ticker: 'AMZN'},
	{name: 'American Airlines', ticker: 'AAL'},
	{name: 'Amgen', ticker: 'AMGN'},
	{name: 'Analog Devices', ticker: 'ADI'},
	{name: 'Apple', ticker: 'AAPL'},
	{name: 'Applied Materials', ticker: 'AMAT'},
	{name: 'Autodesk', ticker: 'ADSK'},
	{name: 'Automatic Data Processing', ticker: 'ADP'},
	{name: 'Baidu', ticker: 'BIDU'},
	{name: 'Bed Bath Beyond', ticker: 'BBBY'},
	{name: 'Biogen', ticker: 'BIIB'},
	{name: 'BioMarin', ticker: 'BMRN'},
	{name: 'Broadcom', ticker: 'AVGO'},
	{name: 'CA Technologies', ticker: 'CA'},
	{name: 'Celgene', ticker: 'CELG'},
	{name: 'Cerner', ticker: 'CERN'},
	{name: 'Charter Communications', ticker: 'CHTR'},
	{name: 'Check Point Software', ticker: 'CHKP'},
	{name: 'Cisco', ticker: 'CSCO'},
	{name: 'Citrix', ticker: 'CTXS'},
	{name: 'Cognizant Technology', ticker: 'CTSH'},
	{name: 'Comcast', ticker: 'CMCSA'},
	{name: 'Costco', ticker: 'COST'},
	{name: 'CSX', ticker: 'CSX'},
	{name: 'CTrip', ticker: 'CTRP'},
	{name: 'Discovery Communications', ticker: 'DISCK'},
	{name: 'Dish Network', ticker: 'DISH'},
	{name: 'Dollar Tree', ticker: 'DLTR'},
	{name: 'eBay', ticker: 'EBAY'},
	{name: 'EA', ticker: 'EA'},
	{name: 'Endo', ticker: 'ENDP'},
	{name: 'Expedia', ticker: 'EXPE'},
	{name: 'Express Scripts', ticker: 'ESRX'},
	{name: 'Facebook', ticker: 'FB'},
	{name: 'Fastenal', ticker: 'FAST'},
	{name: 'Fiserv', ticker: 'FISV'},
	{name: 'Gilead Sciences', ticker: 'GILD'},
	{name: 'Henry Schein', ticker: 'HSIC'},
	{name: 'Illumina', ticker: 'ILMN'},
	{name: 'Incyte', ticker: 'INCY'},
	{name: 'Intel', ticker: 'INTC'},
	{name: 'Intuit', ticker: 'INTU'},
	{name: 'Intuitive Surgical', ticker: 'ISRG'},
	{name: 'JD.com', ticker: 'JD'},
	{name: 'Kraft Heinz', ticker: 'KHC'},
	{name: 'Lam Research', ticker: 'LRCX'},
	//{name: 'Liberty Braves', ticker: 'BATRK'}, //Robinhood doesn't trade this one
	{name: 'Liberty Global', ticker: 'LBTYK'},
	{name: 'Liberty Interactive ', ticker: 'QVCA'},
	{name: 'Liberty Media', ticker: 'LMCK'},
	{name: 'Liberty Ventures', ticker: 'LVNTA'},
	{name: 'Linear Technology', ticker: 'LLTC'},
	{name: 'Marriott', ticker: 'MAR'},
	{name: 'Mattel', ticker: 'MAT'},
	{name: 'Maxim Integrated Products', ticker: 'MXIM'},
	{name: 'Micron', ticker: 'MU'},
	{name: 'Microsoft', ticker: 'MSFT'},
	{name: 'Mondelez', ticker: 'MDLZ'},
	{name: 'Monster Beverage', ticker: 'MNST'},
	//{name: 'Mylan', ticker: 'MYL'}, //APIs fail for this one
	{name: 'NetApp', ticker: 'NTAP'},
	{name: 'NetEase', ticker: 'NTES'},
	{name: 'Netflix', ticker: 'NFLX'},
	{name: 'Norwegian Cruise Line Holdings', ticker: 'NCLH'},
	{name: 'NVIDIA', ticker: 'NVDA'},
	{name: 'NXP', ticker: 'NXPI'},
	{name: "O'Reilly Automotive", ticker: 'ORLY'},
	{name: 'PACCAR', ticker: 'PCAR'},
	{name: 'PayPal', ticker: 'PYPL'},
	{name: 'Paychex', ticker: 'PAYX'},
	{name: 'QUALCOMM', ticker: 'QCOM'},
	{name: 'Regeneron', ticker: 'REGN'},
	{name: 'Ross Stores', ticker: 'ROST'},
	{name: 'SBA', ticker: 'SBAC'},
	{name: 'Seagate', ticker: 'STX'},
	{name: 'Sirius XM', ticker: 'SIRI'},
	{name: 'Skyworks', ticker: 'SWKS'},
	{name: 'Starbucks', ticker: 'SBUX'},
	//{name: 'Stericycle', ticker: 'SRLC'}, //This one never gets any words
	{name: 'Symantec', ticker: 'SYMC'},
	{name: 'Tesla', ticker: 'TSLA'},
	{name: 'Texas Instruments', ticker: 'TXN'},
	{name: 'Priceline', ticker: 'PCLN'},
	{name: 'T-Mobile', ticker: 'TMUS'},
	{name: 'Tractor Supply Company', ticker: 'TSCO'},
	{name: 'TripAdvisor', ticker: 'TRIP'},
	{name: 'Ulta', ticker: 'ULTA'},
	{name: 'Verisk', ticker: 'VRSK'},
	{name: 'Vertex Pharmaceuticals', ticker: 'VRTX'},
	{name: 'Viacom', ticker: 'VIAB'},
	{name: 'Vodafone', ticker: 'VOD'},
	{name: 'Walgreens', ticker: 'WBA'},
	{name: 'Western Digital', ticker: 'WDC'},
	{name: 'Whole Foods', ticker: 'WFM'},
	{name: 'Xilinx', ticker: 'XLNX'},
	{name: 'Yahoo', ticker: 'YHOO'},
];